
#we use java
language: java

#we add the java development kit (jdk)
jdk:
- openjdk8

env:
  - SERVER_IP_ADDRESS=192.168.34.178

before_install: # setup the RSA key for use in Dokku Deployment:
  - ssh-keygen -t rsa -b 4096
  - cd .ssh/
  - scp id_rsa.pub
  -

after_success:
  - ls
  # Use BASH instead of DASH! see: https://ubuntuforums.org/showthread.php?t=1932504